name = "RillRate"
license = "MIT"
licenselink = "https://github.com/rillrate/rillrate/blob/master/LICENSE"
description = "Dynamic tracing system that tends to be real-time. The Guide."
homepage = "https://rillrate.org/"
tags = ["tracing", "metrics", "graphite", "prometheus"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "RillRate OÜ"
  homepage = "https://rillrate.com/"
